# Generated by Django 4.2.20 on 2025-06-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Domicile'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='lieu_naissance',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='mere_nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom de la mère'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='nin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Numéro d'identification national"),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='pere_nom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nom du père'),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='citoyen',
            name='situation_matrimoniale',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], default='celibataire', max_length=20, null=True),
        ),
    ]
