# Generated by Django 4.2.20 on 2025-06-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero_telephone_paiement',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone du paiement'),
        ),
    ]
