# Generated by Django 4.2.20 on 2025-06-04 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0002_paiement_numero_telephone_paiement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='extrait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_cni.extraitnaissance', verbose_name='Extrait de naissance associé'),
        ),
    ]
