# Generated by Django 4.2.20 on 2025-06-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0003_alter_demande_extrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='adresse_sur_cni',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='date_delivrance_cni_precedent',
            field=models.DateField(blank=True, null=True, verbose_name='Date de délivrance CNI précédente'),
        ),
        migrations.AddField(
            model_name='demande',
            name='date_naissance_sur_cni',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='declaration_perte',
            field=models.FileField(blank=True, null=True, upload_to='declarations_perte/', verbose_name='Déclaration de perte'),
        ),
        migrations.AddField(
            model_name='demande',
            name='lieu_naissance_sur_cni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lieu de naissance pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='mere_nom_sur_cni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la mère pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='motif_duplicata',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du duplicata'),
        ),
        migrations.AddField(
            model_name='demande',
            name='nationalite_sur_cni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nationalité pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='nom_sur_cni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom tel qu'il figurera sur la CNI"),
        ),
        migrations.AddField(
            model_name='demande',
            name='numero_cni_precedent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro CNI précédente'),
        ),
        migrations.AddField(
            model_name='demande',
            name='pere_nom_sur_cni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du père pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='prenom_sur_cni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Prénom tel qu'il figurera sur la CNI"),
        ),
        migrations.AddField(
            model_name='demande',
            name='profession_sur_cni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='sexe_sur_cni',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Sexe pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='situation_matrimoniale_sur_cni',
            field=models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, null=True, verbose_name='Situation matrimoniale pour la CNI'),
        ),
        migrations.AddField(
            model_name='demande',
            name='taille_sur_cni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (cm) pour la CNI'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True, verbose_name='Motif du rejet'),
        ),
    ]
