# Generated by Django 4.2.20 on 2025-06-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0004_demande_adresse_sur_cni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='adresse_sur_cni',
        ),
        migrations.AddField(
            model_name='demande',
            name='adresse_residence_sur_cni',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adresse de résidence pour la CNI'),
        ),
    ]
