# Generated by Django 4.2.20 on 2025-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0005_remove_demande_adresse_sur_cni_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demande',
            old_name='mere_nom_sur_cni',
            new_name='nom_mere_sur_cni',
        ),
        migrations.RenameField(
            model_name='demande',
            old_name='pere_nom_sur_cni',
            new_name='nom_pere_sur_cni',
        ),
        migrations.AddField(
            model_name='demande',
            name='numero_extrait_naissance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro de l'extrait de naissance pour la CNI"),
        ),
        migrations.AddField(
            model_name='demande',
            name='photo_fournie',
            field=models.ImageField(blank=True, null=True, upload_to='demandes_photos/', verbose_name='Photo fournie pour la demande'),
        ),
        migrations.AddField(
            model_name='demande',
            name='signature_fournie',
            field=models.ImageField(blank=True, null=True, upload_to='demandes_signatures/', verbose_name='Signature fournie pour la demande'),
        ),
    ]
