# Generated by Django 4.2.20 on 2025-06-10 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0006_rename_mere_nom_sur_cni_demande_nom_mere_sur_cni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='grade',
        ),
    ]
