# Generated by Django 4.2.20 on 2025-06-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0007_remove_agent_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='matricule',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
