# Generated by Django 4.2.20 on 2025-06-10 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0008_alter_agent_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='agent_traitant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_traitees', to='gestion_cni.agent', verbose_name='Agent traitant'),
        ),
    ]
