# Generated by Django 4.2.20 on 2025-06-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cni', '0009_alter_demande_agent_traitant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='adresse_residence_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='date_naissance_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='lieu_naissance_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='nationalite_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='nom_mere_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='nom_pere_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='nom_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='numero_extrait_naissance',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='prenom_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='profession_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='sexe_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='situation_matrimoniale_sur_cni',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='taille_sur_cni',
        ),
        migrations.AddField(
            model_name='citoyen',
            name='mere_prenom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom de la mère'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='pere_prenom',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Prénom du père'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='signe_particulier',
            field=models.TextField(blank=True, null=True, verbose_name='Signe particulier'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='taille',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille (cm)'),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='teint',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Teint'),
        ),
    ]
